services:
  - type: web
    name: hiring-intelligence-api
    runtime: docker
    rootDir: backend
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: postgres
      - key: DB_URL
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: APP_JWT_SECRET
        generateValue: true
      - key: APP_CORS_ORIGINS
        value: https://hiring-intelligence-eight.vercel.app,https://hiring-intelligence-ishwariksh06.vercel.app
