// A second batch of plain-text resumes, in the shape of the Kaggle
// "Updated Resume Dataset". Loaded on demand from the Ingest screen so a demo
// can show fresh resumes flowing through parsing, the ATS check and matching.

const R = (name, email, phone, category, years, skills, degree, college, summary) => ({
  category,
  sourceFile: `${name.replace(/\s+/g, '_')}.txt`,
  rawText: [
    name,
    `${email} | ${phone} | Pune, IN`,
    '',
    'SUMMARY',
    `${summary} ${years} years of experience.`,
    '',
    'SKILLS',
    skills.join(', '),
    '',
    'EXPERIENCE',
    `Cobalt Software — ${category} Engineer (${years} years)`,
    `- Shipped production features using ${skills.slice(0, 3).join(', ')}.`,
    '- Worked in an Agile team alongside product and QA.',
    '',
    'EDUCATION',
    `${degree}, ${college}`,
  ].join('\n'),
});

export const SAMPLE_RESUME_BATCH = [
  R('Farhan Sheikh', 'farhan.sheikh@example.com', '+91 98220 41556', 'Java Backend', 6,
    ['Java', 'Spring Boot', 'Microservices', 'PostgreSQL', 'Kafka', 'AWS', 'Docker'],
    'B.Tech Computer Science', 'COEP Pune',
    'Backend engineer focused on event-driven services and clean domain design.'),
  R('Gauri Kulkarni', 'gauri.kulkarni@example.com', '+91 90110 22781', 'Java Backend', 3,
    ['Java', 'Spring Boot', 'REST APIs', 'Hibernate', 'JUnit'],
    'B.E. Information Technology', 'PICT Pune',
    'Backend developer, comfortable owning a service and its test suite.'),
  R('Nihal Rao', 'nihal.rao@example.com', '+91 99870 33421', 'Frontend', 4,
    ['React', 'TypeScript', 'JavaScript', 'CSS', 'Redux', 'REST APIs'],
    'B.Tech Computer Engineering', 'VJTI Mumbai',
    'Frontend engineer with a focus on accessible, performant interfaces.'),
  R('Aparna Sethi', 'aparna.sethi@example.com', '+91 98333 71290', 'Frontend', 2,
    ['React', 'JavaScript', 'HTML', 'CSS', 'Tailwind CSS'],
    'B.Sc Computer Science', 'SPIT Mumbai',
    'Junior frontend developer building component libraries and dashboards.'),
  R('Tejas Nikam', 'tejas.nikam@example.com', '+91 97640 55112', 'DevOps', 5,
    ['Kubernetes', 'AWS', 'Docker', 'Terraform', 'CI/CD', 'Linux', 'Jenkins'],
    'B.Tech Electronics & Communication', 'NIT Trichy',
    'DevOps engineer running multi-cluster infrastructure and delivery pipelines.'),
  R('Shweta Rane', 'shweta.rane@example.com', '+91 90287 66301', 'DevOps', 2,
    ['Docker', 'AWS', 'Linux', 'CI/CD', 'Python'],
    'B.E. Computer Science', 'DTU',
    'Cloud engineer moving into DevOps, strong on scripting and automation.'),
  R('Kabir Anand', 'kabir.anand@example.com', '+91 98104 90233', 'Data Analyst', 3,
    ['SQL', 'Python', 'Data Analysis', 'Tableau', 'Statistics', 'Excel', 'Power BI'],
    'M.Sc Statistics', 'Fergusson College',
    'Data analyst building leadership dashboards and experiment readouts.'),
  R('Reema Joshi', 'reema.joshi@example.com', '+91 99200 14477', 'Data Analyst', 1,
    ['SQL', 'Excel', 'Data Analysis', 'Statistics'],
    'B.Com', 'Symbiosis Pune',
    'Analyst early in career, strong SQL and reporting fundamentals.'),
  R('Omkar Patil', 'omkar.patil@example.com', '+91 98811 30945', 'Data Engineer', 5,
    ['Python', 'SQL', 'Spark', 'Airflow', 'ETL', 'AWS', 'Kafka'],
    'B.Tech Computer Science', 'IIIT Hyderabad',
    'Data engineer owning ingestion and transformation for an analytics warehouse.'),
  R('Lavanya Iyer', 'lavanya.iyer@example.com', '+91 90045 87220', 'Machine Learning', 4,
    ['Python', 'Machine Learning', 'Deep Learning', 'NLP', 'SQL', 'AWS', 'Docker'],
    'M.Tech Artificial Intelligence', 'IIT Bombay',
    'ML engineer taking forecasting models from notebook to production.'),
  R('Zoya Khan', 'zoya.khan@example.com', '+91 98700 66512', 'Machine Learning', 2,
    ['Python', 'Machine Learning', 'Statistics', 'Data Analysis'],
    'B.Tech Computer Science', 'VIT Vellore',
    'Junior ML engineer with a research background in applied statistics.'),
  R('Aniket More', 'aniket.more@example.com', '+91 97300 41190', 'Mobile', 5,
    ['Kotlin', 'Android', 'Java', 'REST APIs', 'Git', 'CI/CD'],
    'B.E. Computer Science', 'COEP Pune',
    'Android engineer with multiple apps shipped and maintained in the Play Store.'),
  R('Pooja Shah', 'pooja.shah@example.com', '+91 90210 55870', 'Full Stack', 4,
    ['Node.js', 'React', 'JavaScript', 'PostgreSQL', 'REST APIs', 'AWS', 'Express'],
    'B.Tech Information Technology', 'PICT Pune',
    'Full stack engineer shipping features end to end close to product.'),
  R('Rehan Kapadia', 'rehan.kapadia@example.com', '+91 98330 71144', 'QA Automation', 4,
    ['Selenium', 'Java', 'JUnit', 'CI/CD', 'Git', 'REST APIs'],
    'B.Sc Computer Science', 'Mumbai University',
    'QA automation engineer building end-to-end regression suites.'),
  R('Meghana Nair', 'meghana.nair@example.com', '+91 99880 22014', 'Engineering Manager', 11,
    ['Leadership', 'Agile', 'System Design', 'Java', 'Microservices', 'AWS'],
    'B.Tech Computer Science', 'NIT Trichy',
    'Engineering manager who has grown and led backend teams of 8-12.'),
];
